export enum ParticipanteStatus {
    EM_CADASTRAMENTO = "EM_CADASTRAMENTO",
    AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
    AGUARDANDO_CONFIRMACAO_PAGAMENTO = "AGUARDANDO_CONFIRMACAO_PAGAMENTO",
    AGUARDANDO_RETIRADA_CAMISETA = "AGUARDANDO_RETIRADA_CAMISETA",
    FINALIZADO = "FINALIZADO"
}
